/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_recordernote_jni_Speex */

#ifndef _Included_com_android_recordernote_jni_Speex
#define _Included_com_android_recordernote_jni_Speex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_recordernote_jni_Speex
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_recordernote_jni_Speex_init
  (JNIEnv *, jclass);

/*
 * Class:     com_android_recordernote_jni_Speex
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_recordernote_jni_Speex_release
  (JNIEnv *, jclass);

/*
 * Class:     com_android_recordernote_jni_Speex
 * Method:    encode
 * Signature: ([S[B)I
 */
JNIEXPORT jint JNICALL Java_com_android_recordernote_jni_Speex_encode
  (JNIEnv *, jclass, jshortArray, jbyteArray);

/*
 * Class:     com_android_recordernote_jni_Speex
 * Method:    decode
 * Signature: ([B[S)I
 */
JNIEXPORT jint JNICALL Java_com_android_recordernote_jni_Speex_decode
  (JNIEnv *, jclass, jbyteArray, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
